start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

default-root-container-layout = "tiles"
default-root-container-orientation = 'horizontal'

[key-mapping]
    preset = 'qwerty'

[gaps]
    inner.horizontal = 8
    inner.vertical =   8
    outer.left =       8
    outer.bottom =     8
    outer.top =        8
    outer.right =      8

[mode.main.binding]
    alt-slash = 'layout tiles horizontal vertical'
    alt-comma = 'layout accordion horizontal vertical'
    alt-tab = 'workspace-back-and-forth'

    alt-h = 'focus left'
    alt-j = 'focus down'
    alt-k = 'focus up'
    alt-l = 'focus right'

    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

    alt-minus = 'resize smart -50'
    alt-equal = 'resize smart +50'

    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-6 = 'workspace 6'
    alt-7 = 'workspace 7'
    alt-8 = 'workspace 8'
    alt-9 = 'workspace 9'

    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-5 = 'move-node-to-workspace 5'
    alt-shift-6 = 'move-node-to-workspace 6'
    alt-shift-7 = 'move-node-to-workspace 7'
    alt-shift-8 = 'move-node-to-workspace 8'
    alt-shift-9 = 'move-node-to-workspace 9'

    alt-c = 'exec-and-forget open -a "Cursor"'
    alt-o = 'exec-and-forget open -a "Obsidian"'
    alt-t = 'exec-and-forget open -a "iTerm"'
    alt-s = 'exec-and-forget open -a "Slack"'
    alt-b = 'exec-and-forget open -a "Google Chrome"'
    alt-m = 'exec-and-forget open -a "Music"'
    alt-p = 'exec-and-forget open -a "Messages"'
    alt-i = 'exec-and-forget open -a "Linear"'
    alt-e = 'exec-and-forget open -a "Mail"'

[workspace-to-monitor-force-assignment]
    9 = 'secondary'

[[on-window-detected]]
if.app-name-regex-substring = 'Messages'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'Music'
run = 'layout floating'