#!/usr/bin/env bash
#
# Keep skillset-installed work skills out of git.
#
# `skillset install <name>` symlinks shared Knock skills into
# .config/agents-root/.agents/skills/<name>. That directory is itself a git
# submodule (kylemcd/skills); our own skills are real files tracked in that
# submodule's repo, skillset's are symlinks layered on top locally. We ignore
# the symlinks via the submodule's own .git/info/exclude (local-only, lives
# in .git/modules/.../info/exclude) so the internal skill names never land
# in git history — public (.computer) or private (kylemcd/skills) alike.
#
# Re-run this after `skillset install` / `skillset uninstall`.

set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
skills_dir="$repo_root/.config/agents-root/.agents/skills"
begin="# >>> skillset-managed skills (auto-generated by scripts/ignore-skillset-skills.sh) >>>"
end="# <<< skillset-managed skills <<<"

# skills_dir is a git submodule; its exclude file lives in its own git-dir
# (.git/modules/.../info/exclude), not the parent repo's.
git_dir="$(git -C "$skills_dir" rev-parse --absolute-git-dir)"
exclude_file="$git_dir/info/exclude"

cd "$skills_dir"

# Every symlink at the top of the skills dir is a skillset install; paths
# here are relative to skills_dir itself since that's the exclude file's root.
block="$(find . -maxdepth 1 -type l | sed 's|^\./|/|' | sort)"

# Drop any previous managed block, then append a fresh one.
mkdir -p "$(dirname "$exclude_file")"
touch "$exclude_file"
awk -v b="$begin" -v e="$end" '$0==b{s=1;next} $0==e{s=0;next} !s{print}' \
  "$exclude_file" > "$exclude_file.tmp"
{
  cat "$exclude_file.tmp"
  echo "$begin"
  [ -n "$block" ] && echo "$block"
  echo "$end"
} > "$exclude_file"
rm -f "$exclude_file.tmp"

count="$(printf '%s\n' "$block" | grep -c . || true)"
echo "Excluded $count skillset skill(s) from git via ${exclude_file#"$repo_root"/}"
