#!/usr/bin/env bash
#
# Keep skillset-installed work skills out of this (public) repo's git.
#
# `skillset install <name>` symlinks shared Knock skills into
# .config/agents-root/.agents/skills/<name>, which lives inside this repo.
# Our own skills there are real directories; skillset's are symlinks. We ignore
# the symlinks via .git/info/exclude (local-only) so the internal skill names
# never land in this public repo's history.
#
# Re-run this after `skillset install` / `skillset uninstall`.

set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
skills_dir=".config/agents-root/.agents/skills"
exclude_file="$repo_root/.git/info/exclude"
begin="# >>> skillset-managed skills (auto-generated by scripts/ignore-skillset-skills.sh) >>>"
end="# <<< skillset-managed skills <<<"

cd "$repo_root"

# Every symlink in the skills dir is a skillset install; anchor it to the repo root.
block="$(find "$skills_dir" -maxdepth 1 -type l | sort | sed 's|^|/|')"

# Drop any previous managed block, then append a fresh one.
touch "$exclude_file"
awk -v b="$begin" -v e="$end" '$0==b{s=1;next} $0==e{s=0;next} !s{print}' \
  "$exclude_file" > "$exclude_file.tmp"
{
  cat "$exclude_file.tmp"
  echo "$begin"
  [ -n "$block" ] && echo "$block"
  echo "$end"
} > "$exclude_file"
rm -f "$exclude_file.tmp"

count="$(printf '%s\n' "$block" | grep -c . || true)"
echo "Excluded $count skillset skill(s) from git via .git/info/exclude"
